name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Restore dependencies
      run: dotnet restore MySolution.sln

    - name: Build
      run: dotnet build MySolution.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish MyProject/MyProject.csproj -c Release -o ${{github.workspace}}/published

    - name: Zip the publish directory
      run: Compress-Archive -Path ${{github.workspace}}/published/* -DestinationPath ${{github.workspace}}/published.zip

    - name: Upload Artifacts for Deployment
      uses: actions/upload-artifact@v2
      with:
        name: published-app
        path: ${{github.workspace}}/published.zip

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.APP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ${{github.workspace}}/published.zip
